### ISSUE TITLE
Sending commands to second terminal sends original as well

### ISSUE THREAD

**Issue by keithf4** [katacoda/scenario-examples#11]
Following the guidance here to send commands to secondary terminals

https://www.katacoda.com/docs/scenarios/markdown-syntax

When the scenario is started, if that secondary terminal isn't first clicked on to initialize it, the first time a command is sent to it, that command also gets sent to the original terminal. As soon as the secondary (or any further terminals) are created, things then work as expected.

**Comment by thesteve0** [comment]
@BenHall

**Comment by BenHall** [comment]
We've put together a very quick scenario - https://katacoda.com/scenario-examples/scenarios/opening-multiple-terminals

If you are using the T1 \ T2 syntax, then a terminal will open and run the command there. If you have not defined which command to run in, it will run in whichever is active.

Are you seeing different behaviour? Do you have an example you can point us to?

**Comment by keithf4** [comment]
Not sure how you have yours coded to start/use the second terminal. I pre-defined it in the `index.json` so it would have a specific name and be clearer what it's for
```
"environment": {
    "uilayout": "terminal",
    "uimessage1": "\u001b[32mYour Interactive Bash Terminal.\u001b[m\r\n",
    "terminals": [
      {"name": "postgres_terminal", "target": "host01"}
]```
I don't see your T2 terminal being created before the command runs there. So maybe it's an issue when pre-defining it?

**Comment by keithf4** [comment]
Here's an example in a scenario I've been working on. 

https://www.katacoda.com/keithf4/courses/basic-postgresql-for-dbas/setting-up-pg

Go to step 2 and click to run the first command to change to the postgres user. You'll see it gets sent to the first terminal as well as the second if you don't first click the second terminal to initiate it.

**Comment by BenHall** [comment]
@keithf4 Thanks! We've reproduced and fixed the bug. It will be live hopefully later today or tomorrow.

**Comment by keithf4** [comment]
Issue hasn't been fixed, at least in my example scenario above. Now it only runs the command in the wrong terminal and not at all in the target one.

**Comment by keithf4** [comment]
Testing things out again today, it no longer sends the command to the wrong terminal, but it's still not sending it to the second terminal unless it's been initiated first. So this is a lot better than it was because the command can just be clicked again and it goes to the proper place. Thanks for working on this!

**Comment by BenHall** [comment]
@keithf4 Yes, it's now down to a timing issue. We have a quick fix but are looking for a longer term solution. We should have it ready tomorrow.

**Comment by keithf4** [comment]
Sounds good. I'm happy with the current situation for now since it at least doesn't leave the default terminal in a broken state. Thank you!

**Comment by keithf4** [comment]
This issue seems to be fixed and working pretty consistently for me now. Thank you!

**Comment by BenHall** [comment]
@keithf4 Thanks for confirming. Sorry for not updating the ticket. This was deployed a while ago.

Please let us know if you have any other questions.
