### ISSUE TITLE
'none' driver does not support 'minikube ssh' command

### ISSUE THREAD

**Issue by BuddhiWathsala** [katacoda/scenario-examples#17]
I have tried [this sample](https://github.com/katacoda/scenario-examples/tree/master/environment-usages/minikube) to configure a minikube cluster in Katacoda. I have a requirement to ssh to the minikube cluster. But when I ssh it gives an error like below.
```sh
'none' driver does not support 'minikube ssh' command
```

**Comment by BenHall** [comment]
Hi @BuddhiWathsala 

No need to use `minikube ssh` as there is no VM :)  You are already connected and ready to go.
