### ISSUE TITLE
katacoda seems to be blocked from ssh clones on github

### ISSUE THREAD

**Issue by joshuacox** [katacoda/scenario-examples#19]
When cloning using SSH on this scenario:

https://www.katacoda.com/thoth/scenarios/learntocollaboratewithgit

all clones hang indefinitely, looking at an nmap of github show port 22 filtered:

```
Starting Nmap 7.01 ( https://nmap.org ) at 2019-11-02 05:59 UTC
Nmap scan report for github.com (140.82.118.4)
Host is up (0.012s latency).
rDNS record for 140.82.118.4: lb-140-82-118-4-ams.github.com
PORT   STATE    SERVICE
22/tcp filtered ssh
```

yet an  clone works in this scenario:

https://www.katacoda.com/courses/git/3

if the correct keys are added.  The correct keys were also added in the first scenario, so I am uncertain as to what is wrong.

**Comment by BenHall** [comment]
Thanks. Yes, we block SSH outbound, but we aim to whitelist Github however looks like some new IPs hadn't been updated. 

This has been fixed and you should be able to clone from Github over SSH again.

If you need anything, let me know.

**Comment by joshuacox** [comment]
@BenHall are you sure it's working I am getting the same results?

```
git clone git@github.com:GitCertifiedCollaborator/PullRequestCertification.git
Cloning into 'PullRequestCertification'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

```
$ nmap -p 22 github.com

Starting Nmap 7.01 ( https://nmap.org ) at 2019-11-04 14:30 UTC
Nmap scan report for github.com (140.82.118.3)
Host is up (0.010s latency).
rDNS record for 140.82.118.3: lb-140-82-118-3-ams.github.com
PORT   STATE    SERVICE
22/tcp filtered ssh

Nmap done: 1 IP address (1 host up) scanned in 0.55 seconds
```

I cannot re-open this issue, should I make another?

**Comment by BenHall** [comment]
@joshuacox I will check again.

**Comment by BenHall** [comment]
@joshuacox It looks like it might be Github not reporting everything as 140.82.118.4 is not on their IP list at https://api.github.com/meta - Unless I'm missing something.

**Comment by joshuacox** [comment]
I get a similar address when digging from the VM:

```
$ dig github.com +short
140.82.118.3
```

**Comment by joshuacox** [comment]
@BenHall No, we are wrong it is listed as a CIDR:

```
  "git": [
    "192.30.252.0/22",
    "185.199.108.0/22",
    "140.82.112.0/20",
```

**Comment by BenHall** [comment]
@joshuacox Thanks! I had missed that in my search. I'll check now

**Comment by joshuacox** [comment]
I've rarely seen lower than `/24`, this means the first address is 140.82.112.0 and the last is 140.82.127.255 which is kind of weird!
