### ISSUE TITLE
courseData does not seem to work

### ISSUE THREAD

**Issue by tarunaz** [katacoda/scenario-examples#2]
Can you please check what is the issue with this index.json?
The run-init.sh script is never executed. It's referenced in the courseData. I am trying to do a git clone in run-init.sh

{
  "pathwayTitle": "abc",
  "icon": "fa-openshift",
  "title": "abc",
  "description": "abc",
  "difficulty": "beginner",
  "time": "15 minutes",
  "details": {
    "intro": {
      "text": "00-intro.md",
      "courseData": "run-init.sh",
      "code": "env-init.sh"
    },
    "steps": [
      { "title": "Step 1", "text": "01-async-service-interface.md" }
    ],
    "finish": {
      "text": "99-outro.md"
    }
  },
  "files": [],
  "environment": {
    "showdashboard": true,
    "dashboards": [{"name":"Local Web Browser","port":8080},{"name":"OpenShift Console","port":8443}],
    "uilayout": "editor-terminal",
    "uisettings": "java",
    "hideintro": false,
    "uieditorpath": "/root/code",
    "uimessage1": "\u001b[32mYour Interactive Bash Terminal. A safe place to learn and execute commands.\u001b[m\r\n"
  },
  "backend": {
    "imageid": "openshift-middleware-3-7",
    "port": 8443
  }
}

**Comment by BenHall** [comment]
@napcs Thanks for letting us know and I'm very sorry for the frustration.

I've looked at https://github.com/napcs/katacoda-scenarios/blob/master/smallsharptools/changing_dirs/verify.sh

It looks like the Bash environment has a bug when files start with "#!/bin/bash". We'll get this fixed tomorrow.

As for the checking of a users current directory. We execute the script in a separate bash instance meaning it doesn't have access to the users current bash context, meaning we can't get access to the current pwd. Let me investigate a solution.

**Comment by napcs** [comment]
@BenHall I appreciate you looking into this, and for looking in to the completely-unrelated validation stuff I was trying to do. :)

That said I think there's more than just a bug going on with the Bash environment. The configdata script doesn't work there without the shebang line either, as I only added it after peeking at code in a few other people's repos first. Just tried again and no dice.  I get exactly the behavior I need if I move it all to `code` so it's not a showstopper for what I'm trying to get done.

**Comment by BenHall** [comment]
Sorry for not updating the ticket earlier. We've made a number of changes in this area that should fix/improve how courseData works. Please try again and let us know if you have problems again :)
