### ISSUE TITLE
Problem with upload-assets scenario

### ISSUE THREAD

**Issue by supareno** [katacoda/scenario-examples#3]
Hello,

I wrote a first scenario based on the _upload-assets_ scenario: I used the same code and when I push it on GitHub, it didn't work. In the scenario, the _deploy.sh_ script should create a file in the root folder but this file is never created.

In the sample, the path for the shell script are _/opt/..._ but they are copied to _/usr/local/bin/_. I had an error when I launched the scenario. I corrected the path but it does nos work :-( 

So, I used a workaround and it works as expected now : I removed all the code of the shell scripts from the sample and just call my _deploy.sh_.
The code of my scenario is available [here](https://github.com/supareno/katacoda-scenarios/tree/master/learn-shell-scenario).

**Comment by mquinson** [comment]
Same here. I never got the assets to work at the end, so I gave up and now embed all the files I need as uuencoded chunks in my courseData script. I have a sort of pre-compiler for this task, which is here: https://github.com/mquinson/shell-exercises/blob/master/kata-local.py 

An example of file. The source is here: https://github.com/mquinson/shell-exercises/blob/master/usage/piping/piping-setup.sharin while the resulting generated file is here: https://github.com/mquinson/shell-exercises/blob/master/usage/piping/piping-setup.sh

**Comment by sualeh** [comment]
I could not get the _upload-assets_ scenario to work as is. When I changed the backend from _ubuntu_ to _docker_ it worked, though. However, I want to use the _ubuntu_ backend and not _docker_. @BenHall  - any thoughts?

**Comment by BenHall** [comment]
@sualeh Are you using `host01` as the target?

**Comment by sualeh** [comment]
@BenHall - I tried with both `host01` and `client` - neither worked.

**Comment by BenHall** [comment]
@sualeh Do you have an example of your scenarios that we can look at to reproduce?

**Comment by sualeh** [comment]
@BenHall - making one at https://www.katacoda.com/schemacrawler/scenarios/issue-three-temp

**Comment by sualeh** [comment]
@BenHall - please let me know if this example helps you reproduce the issue. Thanks.

**Comment by BenHall** [comment]
@sualeh I've sent you a PR at https://github.com/schemacrawler/SchemaCrawler-Katacoda-Scenarios/pull/1.  I tested it locally and it appears to be working.
