### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by svekars** [katacoda/scenario-examples#30]
I set `environmentsprotocol` to `http` and still getting this:

```
WebSocket connection to 'ws://2886795282-30080-elsy06.environments.katacoda.com' failed: Error during WebSocket handshake: Unexpected response code: 200
```

This is my `index.json`: https://github.com/svekars/katacoda-scenarios/blob/master/getting-started/index.json

**Comment by BenHall** [comment]
Hi @svekars 

It looks like the websocket connection is attempting to use port 30081.

For example: ws://2886795349-30080-elsy02.environments.katacoda.com:30081/

This is not currently support. Instead, it would need to be:

ws://2886795349-30081-elsy02.environments.katacoda.com:80/

I see within the javascript code I see this is possible, but unsure how to set the required variables:

```
      let host = this.paramsFor('application').host;
      let port = this.paramsFor('application').port;
      let path = this.paramsFor('application').path;
```

Please let us know if you need anything else.

**Comment by svekars** [comment]
Thank you for getting back to me so quickly, @BenHall! Is port 80 the only port that works for UI?

**Comment by BenHall** [comment]
@svekars Sorry, I missed your additional question. All ports are available and accessible. More information is at https://www.katacoda.community/accessing-ports-ui.html#using-placeholders-in-scripts
