### ISSUE TITLE
Can I use my docker image as BYO?

### ISSUE THREAD

**Issue by ozbillwang** [katacoda/scenario-examples#32]
Go through the environment (https://www.katacoda.com/docs/scenarios/environments), there are some old systems for choice, but I need install the latest OS patch with some softwares as well. 

What should I do?

How do I build my own environment and backend with nomnated `iamgeid`?

```
"backend": {
  "imageid": "ubuntu"
 }
```
If this `imageid` can be a public docker image with tag, it would be convenience.

```
"backend": {
  "imageid": "node:10"
 }
```
or

```
"backend": {
  "imageid": "python:3-alpine"
 }
```

Or add feature as

```
"backend": {
  "imageid": "docker",
  "imagename": "node:10"
 }
```
Second question, I found other `imageid` in this sample, such as 

```
ubuntu1804
minikube
```
But they are not list in above environment list. Where can I get a full list of enviroiment I can choice?

**Comment by ozbillwang** [comment]
Closed, seems it is only for katacoda subscriptions.

**Comment by BenHall** [comment]
@ozbillwang You are correct, this is only available within the subscription. You can however use the Ubuntu 18.04 environment and download the Docker Image directly.

The complete list of environments can be found at https://www.katacoda.community/environments.html

**Comment by ozbillwang** [comment]
Thanks, @BenHall 

Seems I can only use `ubuntu`, not `ubuntu:2004` and others, such as `kubernetes-cluster:1.18`, etc.

**Comment by BenHall** [comment]
@ozbillwang They should all be available. Could you please retry?

**Comment by ozbillwang** [comment]
@BenHall 

When I set to `kubernetes-cluster:1.18`, I got below error when run `katacoda validate:all`.

```
Validation Error: Image specified in the index.json is not part of the acceptable environment images as specified here: https://katacoda.com/docs/scenarios/environments
```

**Comment by BenHall** [comment]
@ozbillwang Thanks! We'll get the API updated to reflect this new image and the validate environment list.
