### ISSUE TITLE
Custom width of tutorial section

### ISSUE THREAD

**Issue by derberg** [katacoda/scenario-examples#34]
Hi. I noticed https://github.com/katacoda/scenario-examples/blob/master/assets/test.css but I tried and it did not have any effect on the scenario. Is this implemented?

**Comment by BenHall** [comment]
@derberg Within our subscription, you can customise the width when embedding Katacoda into your own documentation. This is an example of what the CSS looks like when using this API.

Currently you can't change the look/feel of the layout on katacoda.com to ensure a consistent user experience.
