### ISSUE TITLE
UI not working in case of kubectl port forward

### ISSUE THREAD

**Issue by kumarlalapet** [katacoda/scenario-examples#35]
Hello,

I deployed a k8s service in my scenario and doing a port forward as below

```
$ kubectl --namespace default port-forward svc/imply-manager-int 9097
Forwarding from 127.0.0.1:9097 -> 9097
Forwarding from [::1]:9097 -> 9097
```

And the URL below is not working

```
https://2886795288-9097-ollie09.environments.katacoda.com/
```

Any help is much appreciated. Thank you.

**Comment by gsoria** [comment]
hi @kumarlalapet could yous point us to the URL and sources of your scenario where you have the issue?

**Comment by kumarlalapet** [comment]
Hi @gsoria Thank you for the response. Really appreciate it.

Im installing a Kubernetes service - https://kubernetes.io/docs/concepts/services-networking/service/ - and that service exposes a port 9097.

Im following the documentation here - https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/ - and forwarding that port 9097 to my ubuntu image in katacoda

And Im expecting the URL as explained in this documentation - https://www.katacoda.com/docs/scenarios/displaying-ports

https://[[HOST_SUBDOMAIN]]-9097-[[KATACODA_HOST]].environments.katacoda.com/

And thats not working.

**Comment by gsoria** [comment]
@kumarlalapet this example may be of help https://www.katacoda.com/courses/kubernetes/networking-introduction

**Comment by kumarlalapet** [comment]
HI @gsoria, yes I did follow that. However I also did a port forward like below at the end of step 1

`kubectl --namespace default port-forward svc/webapp1-clusterip-svc 80`

And when I do `curl` to `localhost` like below it works.

`
master $ curl localhost:80
This request was processed by host: webapp1-clusterip-deployment-669c7c65c4-4rnch
`

However when I access the same in the browser it does not - https://2886795270-80-frugo04.environments.katacoda.com/ - and says the below message

`
Connecting to Port 80
We're currently trying to connect to a HTTP service running on 80. Services can sometimes take a few moments to start, even upto five minutes.
`

**Comment by BenHall** [comment]
@kumarlalapet By default, Kube Proxy only accepts connections from localhost as it only listens on 127.0.0.1 for security / dev purposes.

```
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

You can explicitly bind to 0.0.0.0 by setting it as the address. This will make it available via the Katacoda URL and to your browser.

```
$ kubectl proxy  --address=0.0.0.0
Starting to serve on [::]:8001
```
