### ISSUE TITLE
Does katacoda dashboards support websocket?

### ISSUE THREAD

**Issue by hengyunabc** [katacoda/scenario-examples#4]
Normal http access is OK, but WebSocket opening handshake timed out.

**Comment by BenHall** [comment]
Sorry for the delayed response, the notifications on the repository had been disabled. Yes, we do support websockets. What application/port are you using? If you send us an example we can investigate.

**Comment by hengyunabc** [comment]
@BenHall Sorry for the delayed response.

### start scenario

https://katacoda.com/hengyunabc/scenarios/arthas-advanced-en

Just use this scenario to start the following websocket sample.

### start websocket sample

https://github.com/spring-guides/gs-messaging-stomp-websocket/tree/2.1.4.RELEASE

```
wget https://github.com/spring-guides/gs-messaging-stomp-websocket/archive/2.1.4.RELEASE.zip
unzip 2.1.4.RELEASE.zip
cd gs-messaging-stomp-websocket-2.1.4.RELEASE/complete
./mvnw spring-boot:run -Dserver.port=80
```

### visit port 80

Click `Connect` button.

![image](https://user-images.githubusercontent.com/1683936/56630817-3a852a80-6685-11e9-9604-76eb02e25248.png)

**Comment by BenHall** [comment]
Within the scenario index.json, If you set the `backend.environmentsprotocol` element to `http` then it should resolve the issue. The issue is because we are proxying based on HTTPS when it requires HTTP.

**Comment by BenHall** [comment]
Also in your sidebar link use http

**Comment by hengyunabc** [comment]
Nginx error now?

I start this scenario:
https://katacoda.com/scenario-examples/scenarios/displaying-web-ui

`curl localhost` is OK:

![image](https://user-images.githubusercontent.com/1683936/56648835-94eaaf00-66b6-11e9-95cf-693cd73ddfed.png)

But web ui return 502: 

![image](https://user-images.githubusercontent.com/1683936/56648899-b350aa80-66b6-11e9-8c7f-2d9cbbc8d876.png)

**Comment by BenHall** [comment]
Could you try again please?

**Comment by hengyunabc** [comment]
@BenHall Nginx is OK now.

After set `"environmentsprotocol": "http"`, the websocket is OK. 

Thank you very much.

---

This page has a broken link: https://katacoda.com/docs/scenarios/index-json

![image](https://user-images.githubusercontent.com/1683936/56650739-3b847f00-66ba-11e9-9c04-e8dcd39c42f5.png)

https://github.com/katacoda/scenario-examples/blob/master/example-index-json/index.jsonschema
