### ISSUE TITLE
courseData is not executed for scenario marked as hideIntro

### ISSUE THREAD

**Issue by mquinson** [katacoda/scenario-examples#9]
Hello,

in my current exercises, I don't use the intro screen. But if I do add 
```
    "hideintro": true,
```

then my courseData and code scripts are simply not executed. So my learners have to click on "continue" of a blank page just to get these scripts to start.

**Comment by BenHall** [comment]
Thanks for letting us know. We should have a fix live by Monday.

**Comment by BenHall** [comment]
Sorry for not updating the issue. This has been fixed.
